export const Meetups = [
    {
        id: 20241125,
        community: "graz",
        date: "2024-11-25",
        timeStart: "5pm",
        timeEnd: "12pm",
        location: "SPACELEND",
        locationAddress: "yoMama",
        locationGmapsUrl: "https://adsf.com",
        locationOpenStreetUrl: "https://adsf.com",
    }, {
        id: 20241126,
        community: "graz",
        date: "2024-11-26",
        timeStart: "5pm",
        timeEnd: "12pm",
        location: "SPACELEND",
        locationAddress: "yoMama",
        locationGmapsUrl: "https://adsf.com",
        locationOpenStreetUrl: "https://adsf.com",
    }, {
        id: 20241127,
        community: "vienna",
        date: "2024-11-27",
        timeStart: "5pm",
        timeEnd: "12pm",
        location: "SPACELEND",
        locationAddress: "yoMama",
        locationGmapsUrl: "https://adsf.com",
        locationOpenStreetUrl: "https://adsf.com",
    }, {
        id: 20241128,
        community: "vienna",
        date: "2024-11-28",
        timeStart: "5pm",
        timeEnd: "12pm",
        location: "SPACELEND",
        locationAddress: "yoMama",
        locationGmapsUrl: "https://adsf.com",
        locationOpenStreetUrl: "https://adsf.com",
    },
]